formatter: "md doc" # this is required

version: ""

header-from: "main.tf"
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show:
    - all

content: |-
  {{ .Header }}
  # Clumio AWS Terraform Module

  Terraform module to install the Clumio required AWS resources in the customer AWS account.

  ## Usage
  This module is to be used along with the resource clumio_aws_connection as some of the inputs for the module are obtained from the output of clumio_aws_connection resource.
  Below is an example of using the module:

  ```hcl
  {{ include "examples/all_data_sources/main.tf" }}
  ```
  
  An additional `is_ec2_mssql_enable` flag is supported for legacy connections. Please contact the Support Team if you need assistance with enabling it.

  ## Upgrading module
  Run the following terraform commands to upgrade from a older version of the module.
  ```terraform
  terraform init -upgrade
  terraform plan
  terraform apply
  ```
  Note: If the module block has explicit version specified, then the version must be changed before running the above commands.
  
  For example, in the below config the module has version 0.26.0 as shown below:
  ```hcl
  module "clumio_aws_connection_module" {
    providers = {
    aws    = aws
    clumio = clumio
    }
    source                = "../../"
    version               = "0.26.0"
    clumio_token          = clumio_aws_connection.test_conn.token
    role_external_id      = clumio_aws_connection.test_conn.role_external_id
    aws_region            = clumio_aws_connection.test_conn.aws_region
    aws_account_id        = data.aws_caller_identity.current.account_id
    clumio_aws_account_id = clumio_aws_connection.test_conn.clumio_aws_account_id
    is_ebs_enabled        = true
    is_rds_enabled        = true
    is_s3_enabled         = true
    is_dynamodb_enabled   = true
  }
  ```
  To upgrade the module version to 0.27.0, the version number should be updated in the config as shown below.
  ```hcl
  module "clumio_aws_connection_module" {
    providers = {
    aws    = aws
    clumio = clumio
    }
    source                = "../../"
    version               = "0.27.0"
    clumio_token          = clumio_aws_connection.test_conn.token
    role_external_id      = clumio_aws_connection.test_conn.role_external_id
    aws_region            = clumio_aws_connection.test_conn.aws_region
    aws_account_id        = data.aws_caller_identity.current.account_id
    clumio_aws_account_id = clumio_aws_connection.test_conn.clumio_aws_account_id
    is_ebs_enabled        = true
    is_rds_enabled        = true
    is_s3_enabled         = true
    is_dynamodb_enabled   = true
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
